// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";


export type AddTodoReturns = {
  "id": string;
};

export async function addTodo(client: Executor): Promise<AddTodoReturns> {
  return client.queryRequiredSingle(`\
insert Todos {
  name := "jadi kaya",
  value := "kerja--invest--kerja--invest--pensiun"
}`);

}
