// GENERATED by @edgedb/generate v0.4.1

import { User } from 'dbschema/interfaces';
import type { Executor } from 'edgedb';

export type AddUserReturns = {
  id: string;
};

export async function addUser(
  client: Executor,
  userData: User,
): Promise<AddUserReturns> {
  return client.queryRequiredSingle(`\
insert User{
    username := "${userData.username}",
    password := "${userData.password}" 
  }`);
}
