// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";


export type DeleteTodoReturns = {
  "id": string;
}[];

export async function deleteTodo(client: Executor): Promise<DeleteTodoReturns> {
  return client.query(`\
with module default
delete (select Todos 
        filter Todos.name = 'todo dua');`);

}
