// GENERATED by @edgedb/generate v0.4.1

import type { Executor } from 'edgedb';

export type GetUserReturns = {
  id: string;
  username: string;
  password: string;
}[];

export async function getUser(
  client: Executor,
  userData: { username: string },
): Promise<GetUserReturns> {
  return client.query(`\
select User {
    *
  } 
filter User.username = "${userData.username}"
`);
}
